[patch]
title = "洛克人EXE6 中文化"
authors = ["洛克人EXE6 爱好者汉化组 <352415346@qq.com>"]
source = "https://www.rockmanlab.com/forum.php?mod=viewthread&tid=43465"

[versions.'1.0.0']
netplay_compatibility = "exe6"

[versions.'1.0.0'.saveedit_overrides.strings]
chips = [
    "",
    "加农炮",
    "高级加农炮",
    "超级加农炮",
    "空气射击",
    "火神炮1",
    "火神炮2",
    "火神炮3",
    "超级火神炮",
    "散弹枪1",
    "散弹枪2",
    "散弹枪3",
    "战车炮1",
    "战车炮2",
    "战车炮3",
    "太阳枪1",
    "太阳枪2",
    "太阳枪3",
    "太阳枪EX",
    "溜溜球",
    "地狱火焰1",
    "地狱火焰2",
    "地狱火焰3",
    "阔水箭",
    "连环箭1",
    "连环箭2",
    "连环箭3",
    "海星炮1",
    "海星炮2",
    "海星炮3",
    "电球",
    "玩偶闪电1",
    "玩偶闪电2",
    "玩偶闪电3",
    "电气脉冲1",
    "电气脉冲2",
    "电气脉冲3",
    "危机蜜蜂1",
    "危机蜜蜂2",
    "危机蜜蜂3",
    "滚木1",
    "滚木2",
    "滚木3",
    "机枪1",
    "机枪2",
    "机枪3",
    "火龙",
    "电龙",
    "水龙",
    "木龙",
    "空气曲棍球",
    "钻头臂",
    "龙卷风",
    "噪音风暴",
    "迷你炸弹",
    "能量炸弹",
    "高级能量炸弹",
    "闪光弹1",
    "闪光弹2",
    "闪光弹3",
    "黑色炸弹",
    "刺球针1",
    "刺球针2",
    "刺球针3",
    "玉米射击1",
    "玉米射击2",
    "玉米射击3",
    "bug炸弹",
    "草地种子",
    "冰地种子",
    "毒地种子",
    "短剑",
    "阔剑",
    "长剑",
    "阔刃剑",
    "长刃剑",
    "火焰剑",
    "碧水剑",
    "电气剑",
    "木叶剑",
    "风神扇",
    "踏前斩",
    "变幻剑",
    "新颖变幻剑",
    "圆月弯刀",
    "妖刀村正",
    "机械剑",
    "元素剑",
    "暗杀剑",
    "飞地板",
    "双重飞地",
    "三重飞地",
    "地震波1",
    "地震波2",
    "地震波3",
    "辉光石脑1",
    "辉光石脑2",
    "辉光石脑3",
    "小煮壶1",
    "小煮壶2",
    "小煮壶3",
    "沙虫1",
    "沙虫2",
    "沙虫3",
    "风轮1",
    "风轮2",
    "风轮3",
    "火焰拳1",
    "火焰拳2",
    "火焰拳3",
    "燃烧立方1",
    "燃烧立方2",
    "燃烧立方3",
    "杀人眼感应器1",
    "杀人眼感应器2",
    "杀人眼感应器3",
    "回旋镖",
    "高级回旋镖",
    "超级回旋镖",
    "背刺竹",
    "巨人拳1",
    "巨人拳2",
    "巨人拳3",
    "穿山铁壳1",
    "穿山铁壳2",
    "穿山铁壳3",
    "风轮1",
    "风轮2",
    "风轮3",
    "吹风机",
    "吸风机",
    "反射盾1",
    "反射盾2",
    "反射盾3",
    "家门蛇",
    "梦魇召唤1",
    "梦魇召唤2",
    "梦魇召唤3",
    "数字球",
    "流星群",
    "正义之拳",
    "破地炮",
    "环绕枪",
    "石块",
    "计数炸弹1",
    "隐蔽地雷",
    "无敌喇叭",
    "混乱喇叭",
    "地震喇叭",
    "失明喇叭",
    "诅咒人偶",
    "地藏王",
    "毒阿努比斯",
    "天鼓大人",
    "回复10",
    "回复30",
    "回复50",
    "回复80",
    "回复120",
    "回复150",
    "回复200",
    "回复300",
    "占格",
    "占地",
    "占地惩罚",
    "占地复仇",
    "地板复原",
    "死亡竞赛",
    "圣格",
    "圣地",
    "来之路",
    "去之路",
    "慢槽",
    "快槽",
    "满槽",
    "火力修正",
    "错误修正",
    "隐身",
    "防护罩10",
    "防护罩100",
    "防护罩200",
    "泡泡护罩",
    "梦幻辉光",
    "磁力圈",
    "白色胶囊",
    "卸载",
    "领航员反叛",
    "替身攻击",
    "空手夺刃",
    "回复毒药",
    "伤害复制",
    "体力同步",
    "攻击+10",
    "领航员+20",
    "单色点",
    "攻击+30",
    "双色点",
    "元素陷阱",
    "卡尼路士兵",
    "雪球",
    "计数炸弹2",
    "计数炸弹3",
    "巨型炸弹",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "萝露",
    "萝露V2",
    "萝露V3",
    "布鲁斯",
    "布鲁斯EX",
    "布鲁斯SP",
    "灼热人",
    "灼热人EX",
    "灼热人SP",
    "电气人",
    "电气人EX",
    "电气人SP",
    "切裂人",
    "切裂人EX",
    "切裂人SP",
    "杀手人",
    "杀手人EX",
    "杀手人SP",
    "火车人",
    "火车人EX",
    "火车人SP",
    "水泡人",
    "水泡人EX",
    "水泡人SP",
    "战斧人",
    "战斧人EX",
    "战斧人SP",
    "天狗人",
    "天狗人EX",
    "天狗人SP",
    "大地人",
    "大地人EX",
    "大地人SP",
    "垃圾人",
    "垃圾人EX",
    "垃圾人SP",
    "爆炎人",
    "爆炎人EX",
    "爆炎人SP",
    "潜水人",
    "潜水人EX",
    "潜水人SP",
    "马戏人",
    "马戏人EX",
    "马戏人SP",
    "审判人",
    "审判人EX",
    "审判人SP",
    "元素人",
    "元素人EX",
    "元素人SP",
    "卡尼路",
    "卡尼路EX",
    "卡尼路SP",
    "伯爵",
    "伯爵EX",
    "伯爵SP",
    "强戈",
    "强戈V2",
    "强戈V3",
    "火焰拳臂",
    "刺球针臂",
    "闪电臂",
    "回旋镖臂",
    "同步触发器",
    "黑暗剑",
    "黑暗电球",
    "黑暗恢复",
    "黑暗隐身",
    "黑暗附加",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "佛鲁迪",
    "百万拳击",
    "布鲁斯三角斩",
    "卡尼路军队",
    "碎片黑暗阔剑",
    "佛鲁迪+",
    "流星连拳",
    "卡尼路交叉斩",
    "彩斗装甲",
    "碎片死亡电球",
    "双重兽化",
    "麒麟",
    "凤凰",
    "",
    "蝙蝠炮1",
    "蝙蝠炮2",
    "蝙蝠炮3",
    "蝙蝠炮4",
    "兽化",
    "巨型加农炮1",
    "巨型加农炮2",
    "巨型加农炮3",
    "宽阔火焰1",
    "宽阔火焰2",
    "宽阔火焰3",
    "火焰巨拳1",
    "火焰巨拳2",
    "火焰巨拳3",
    "能量冲击波1",
    "能量冲击波2",
    "能量冲击波3",
    "玉米聚会",
    "平衡铁壳",
    "破坏脉冲",
    "巨型计数炸弹",
    "汹涌石脑",
    "超级阔水箭",
    "超级散弹枪",
    "梦幻剑",
    "巨型溜溜球",
    "地狱曲棍球",
    "毒法老像",
    "保镖",
    "双重英雄",
    "暗黑救世主",
    "融合大师",
    "红日蓝月",
    "双重领袖",
    "太阳同盟",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "冰块",
    "Z圣光剑",
    "白色胶囊",
    "紫色胶囊",
    "粉色胶囊",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "灼热重压",
    "冲刺电气剑",
    "滚动切裂",
    "杀手死亡光线",
    "火山碳充能",
    "水泡淋浴",
    "鹰击战斧",
    "风神龙卷",
    "滚动钻头突",
    "垃圾粉碎",
    "踏前斩",
]
ncps = [
    "",
    "超级装甲",
    "选卡上限+1",
    "选卡上限+2",
    "高级芯片夹+1",
    "高级芯片夹+2",
    "究极芯片夹+1",
    "初始防护罩",
    "盾牌",
    "反射盾",
    "替身魔术",
    "浮游鞋",
    "空气鞋",
    "紧身衣",
    "检索洗牌",
    "数字展开",
    "潜行",
    "油性身体",
    "我是鱼",
    "电池模式",
    "丛林地带",
    "收藏夹之眼",
    "百万富翁",
    "幽默感",
    "韵律诗歌",
    "滑冰鞋",
    "自我回复",
    "火力套装",
    "身体套装",
    "芯片夹套装1",
    "芯片夹套装2",
    "漏洞终止器",
    "莱西支援",
    "比特支援",
    "探戈支援",
    "攻击+1",
    "连射+1",
    "储气+1",
    "攻击MAX",
    "连射MAX",
    "储气MAX",
    "HP+50",
    "HP+100",
    "HP+200",
    "HP+300",
    "HP+400",
    "HP+500",
]
modcards = [
    "",
    "加农炮塔",
    "泡泡蟹",
    "冻熊",
    "地雷熊",
    "石脑",
    "陨石法师",
    "树种花",
    "剑影",
    "破地战车",
    "重哑铃",
    "洋葱藤",
    "占地果冻",
    "火山炮",
    "序号柱",
    "磁力虫",
    "木蜘蛛",
    "炸弹小子",
    "长鼻草",
    "电灯泡",
    "电气鬼",
    "火炉",
    "刺球鱼",
    "海星",
    "墨镜怪",
    "稻草偶",
    "小飞机",
    "石人像",
    "穿山鼠",
    "沸水壶",
    "壶龙",
    "数字人",
    "冰冻人",
    "骷髅人",
    "影子人",
    "剪刀人",
    "骑士人",
    "蟾蜍人",
    "磁力人",
    "行星人",
    "野兽人",
    "沙漠人",
    "大和人",
    "影像人",
    "燃烧人",
    "星星人",
    "暴雪人",
    "燕子人",
    "切裂人",
    "杀手人",
    "大地人",
    "垃圾人",
    "爆炎人",
    "马戏人",
    "炸弹手套",
    "散弹河豚",
    "海浪水母",
    "淤泥包",
    "人工卫星",
    "召雷机",
    "摇摆电球",
    "泡泡章鱼",
    "弓箭贝",
    "磁力蟋蟀",
    "陨石巫师",
    "挖地鼠",
    "针刺机器",
    "双子星",
    "飞牙海狮",
    "侧面竹",
    "火图腾",
    "封闭炮塔",
    "骷髅骨",
    "火圈海马",
    "潜水艇",
    "烛台",
    "机枪炮塔",
    "电箱",
    "爆爆玉米",
    "草堆球",
    "蜂巢",
    "梦魇",
    "沙地虫",
    "暗杀机器",
    "石头人",
    "彩色人",
    "鲨鱼人",
    "法老人",
    "空气人",
    "冻结人",
    "闪电人",
    "汽油人",
    "植物人",
    "迷雾人",
    "保龄人",
    "黑暗人",
    "陀螺人",
    "剑道人",
    "寒冷人",
    "检索人",
    "巨云人",
    "榄球人",
    "火车人",
    "天狗人",
    "潜水人",
    "审判人",
    "元素人",
    "庞克",
    "黑暗洛克人",
    "灵魂斗士改装",
    "名人超绝改装",
    "佛鲁迪BX",
    "强戈",
    "伯爵",
    "洛克人Zero",
    "电脑兽麒麟",
    "电脑兽凤凰",
    "佛鲁迪共鸣洛克人",
]
